import { z } from 'zod';
import * as fs from 'fs';
import * as path from 'path';

import {
  OBSIDIAN_VAULT_PATH,
  SYNC_DIR_NAME,
  DASHBOARD_NAME,
  SYNC_STATE_FILENAME,
  DEFAULT_SYNC_DAYS,
  DEFAULT_SUMMARY_KEYS,
} from '../constants';
import { DailySummaryDay, DailyMetric, CivilDate, ToolResult } from '../types';
import { buildDailySummary } from './summary';
import { civilDaysAgo, civilToISODate, isoDateToCivil } from '../lib/civil';

interface SyncState { lastSyncedDate?: string; }

function vaultOrThrow(): string {
  if (!OBSIDIAN_VAULT_PATH) {
    throw new Error('OBSIDIAN_VAULT_PATH is not set — Obsidian sync is disabled. Set it in .env to enable.');
  }
  return OBSIDIAN_VAULT_PATH;
}

function statePath(vault: string): string {
  return path.join(vault, SYNC_DIR_NAME, SYNC_STATE_FILENAME);
}

function loadState(vault: string): SyncState {
  const p = statePath(vault);
  if (!fs.existsSync(p)) return {};
  try { return JSON.parse(fs.readFileSync(p, 'utf-8')) as SyncState; } catch { return {}; }
}

function saveState(vault: string, state: SyncState): void {
  const p = statePath(vault);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, JSON.stringify(state, null, 2));
}

// Map a metric to a Dataview-friendly (field, value) for frontmatter.
function frontmatterField(m: DailyMetric): [string, number] | null {
  if (m.value === null) return null;
  switch (m.key) {
    case 'steps': return ['steps', Math.round(m.value)];
    case 'distance': return ['distance_km', Number((m.value / 1_000_000).toFixed(2))]; // mm → km
    case 'activeCalories': return ['active_calories', Math.round(m.value)];
    case 'activeZoneMinutes': return ['active_zone_minutes', Math.round(m.value)];
    case 'floors': return ['floors', Math.round(m.value)];
    case 'restingHeartRate': return ['resting_hr', Math.round(m.value)];
    case 'heartRateAvg': return ['heart_rate_avg', Math.round(m.value)];
    case 'heartRateMax': return ['heart_rate_max', Math.round(m.value)];
    case 'heartRateMin': return ['heart_rate_min', Math.round(m.value)];
    default: return [m.key, m.value];
  }
}

function renderDayNote(day: DailySummaryDay): string {
  const fmFields: string[] = [`date: ${day.date}`, 'type: health-day'];
  const bodyLines: string[] = [];
  for (const key of Object.keys(day.metrics)) {
    const ff = frontmatterField(day.metrics[key]);
    if (ff) {
      fmFields.push(`${ff[0]}: ${ff[1]}`);
      bodyLines.push(`- **${ff[0].replace(/_/g, ' ')}**: ${ff[1]}`);
    }
  }
  return [
    '---',
    ...fmFields,
    '---',
    '',
    `# Health — ${day.date}`,
    '',
    bodyLines.length ? bodyLines.join('\n') : '_No metric values recorded for this day._',
    '',
  ].join('\n');
}

function avg(nums: number[]): number | null {
  const vals = nums.filter(n => Number.isFinite(n));
  return vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : null;
}

function renderDashboard(days: DailySummaryDay[]): string {
  const window = (n: number) => days.slice(-n);
  const valuesFor = (subset: DailySummaryDay[], key: string): number[] =>
    subset.map(d => d.metrics[key]?.value).filter((v): v is number => v != null);

  const block = (label: string, subset: DailySummaryDay[]): string => {
    const steps = avg(valuesFor(subset, 'steps'));
    const distKm = valuesFor(subset, 'distance').reduce((a, b) => a + b, 0) / 1_000_000; // mm → km
    const cals = avg(valuesFor(subset, 'activeCalories'));
    const azm = avg(valuesFor(subset, 'activeZoneMinutes'));
    const floors = valuesFor(subset, 'floors').reduce((a, b) => a + b, 0);
    const restHr = avg(valuesFor(subset, 'restingHeartRate'));
    const hrAvg = avg(valuesFor(subset, 'heartRateAvg'));
    return [
      `### ${label} (${subset.length} day${subset.length === 1 ? '' : 's'})`,
      `- Avg steps: ${steps != null ? Math.round(steps).toLocaleString() : '—'}`,
      `- Total distance: ${distKm ? distKm.toFixed(1) + ' km' : '—'}`,
      `- Avg active calories: ${cals != null ? Math.round(cals) + ' kcal' : '—'}`,
      `- Avg active-zone minutes: ${azm != null ? Math.round(azm) : '—'}`,
      `- Total floors: ${floors ? Math.round(floors) : '—'}`,
      `- Avg resting HR: ${restHr != null ? Math.round(restHr) + ' bpm' : '—'}`,
      `- Avg HR: ${hrAvg != null ? Math.round(hrAvg) + ' bpm' : '—'}`,
      '',
    ].join('\n');
  };

  const latest = days.length ? days[days.length - 1].date : 'n/a';
  return [
    '---',
    'type: health-dashboard',
    `updated: ${latest}`,
    '---',
    '',
    '# Health Dashboard',
    '',
    `Most recent day with data: **${latest}**`,
    '',
    block('Last 7 days', window(7)),
    block('Last 30 days', window(30)),
    '',
    '_Generated by google-health-mcp-server. Source of truth is the per-day notes in `Lifestyle/Health/`._',
    '',
  ].join('\n');
}

/** Core sync routine, shared by the MCP tool and the CLI/cron. */
export async function runSync(opts: { days?: number; fullSync?: boolean; startDate?: string; endDate?: string }) {
  const vault = vaultOrThrow();
  const state = loadState(vault);

  const endCivil: CivilDate = opts.endDate ? isoDateToCivil(opts.endDate) : civilDaysAgo(0);
  let startCivil: CivilDate;
  if (opts.startDate) {
    startCivil = isoDateToCivil(opts.startDate);
  } else if (opts.fullSync || !state.lastSyncedDate) {
    startCivil = civilDaysAgo((opts.days ?? DEFAULT_SYNC_DAYS) - 1);
  } else {
    // Incremental: re-pull from the last synced day (catches late-arriving data).
    startCivil = isoDateToCivil(state.lastSyncedDate);
  }

  const days = await buildDailySummary(startCivil, endCivil, DEFAULT_SUMMARY_KEYS);

  const notesDir = path.join(vault, SYNC_DIR_NAME);
  fs.mkdirSync(notesDir, { recursive: true });
  let written = 0;
  for (const day of days) {
    fs.writeFileSync(path.join(notesDir, `${day.date}.md`), renderDayNote(day));
    written += 1;
  }

  // The dashboard needs a longer window than just the incremental slice; pull 30d for it.
  const dashStart = civilDaysAgo(29);
  const dashDays = await buildDailySummary(dashStart, endCivil, DEFAULT_SUMMARY_KEYS);
  fs.writeFileSync(path.join(vault, DASHBOARD_NAME), renderDashboard(dashDays));

  if (days.length) saveState(vault, { lastSyncedDate: days[days.length - 1].date });

  return { written, dashboardDays: dashDays.length, lastDate: days.length ? days[days.length - 1].date : null };
}

// ---- MCP tool ----
export const syncHealthInputSchema = {
  days: z.number().int().min(1).max(366).optional()
    .describe('Window size for a full sync (days ending today). Default 30. Ignored when start_date is set.'),
  full_sync: z.boolean().optional()
    .describe('Re-render the whole window from scratch instead of incrementally from the last sync.'),
  start_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe('Explicit start date YYYY-MM-DD.'),
  end_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe('Explicit end date YYYY-MM-DD. Default today.'),
};

export async function syncHealthToObsidian(args: {
  days?: number;
  full_sync?: boolean;
  start_date?: string;
  end_date?: string;
}): Promise<ToolResult> {
  const r = await runSync({
    days: args.days,
    fullSync: args.full_sync,
    startDate: args.start_date,
    endDate: args.end_date,
  });
  return {
    content: [{
      type: 'text' as const,
      text: `Synced ${r.written} day note(s) to ${SYNC_DIR_NAME}/ and refreshed the dashboard ` +
        `(${r.dashboardDays} days). Last day with data: ${r.lastDate ?? 'none'}.`,
    }],
  };
}

/** Entry point for `npm run sync` (what the launchd cron invokes). */
export async function syncCli(): Promise<void> {
  const r = await runSync({});
  process.stderr.write(
    `Google Health sync complete: ${r.written} day note(s), dashboard ${r.dashboardDays} days, ` +
    `last date ${r.lastDate ?? 'none'}.\n`,
  );
}
